"""
Django settings for TaxComplianceProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.staticfiles.finders import find as staticfiles_find
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Application definition

# TaxComplianceProject/settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tax_processor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TaxComplianceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TaxComplianceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        # Recommended option for ensuring proper transaction handling and data integrity
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4', # Ensure full Unicode support
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected')
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'),
]

# --- ADD THIS LINE FOR WHITENOISE ---
STATIC_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# -------------------------------------------------------------
# CRITICAL FIX: Dynamically find the absolute path to Admin static files
# using the finders framework, which resolves cross-platform differences.
# -------------------------------------------------------------

# Use staticfiles_find to locate a file guaranteed to be in the Admin static directory (like admin/css/base.css)
# and then grab the root directory where it was found.

# This function might return None if run too early, so we wrap it in a try-block
try:
    admin_base_css_path = staticfiles_find('admin/css/base.css')
    if admin_base_css_path:
        # Navigate from the file path back up to the base 'admin/static' directory
        # In Linux: .../venv/lib/pythonX.X/site-packages/django/contrib/admin/static/admin/css/base.css
        # In Windows: .../venv/Lib/site-packages/django/contrib/admin/static/admin/css/base.css

        # We need to go up three levels from 'base.css' to get to the 'static' folder base.
        admin_static_root = os.path.dirname(os.path.dirname(os.path.dirname(admin_base_css_path)))

        # Add the dynamically found Admin root to the list of search directories
        STATICFILES_DIRS.append(admin_static_root)
except Exception:
    # Fail gracefully if the finders framework is not fully initialized yet
    pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# custom loging redirects
LOGIN_REDIRECT_URL = '/'  # The new dashboard URL is the root
LOGOUT_REDIRECT_URL = '/login/' # The new login page URL
LOGIN_URL = '/login/' # The new login page URL
