# Generated by Django 5.2.7 on 2025-10-18 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Q3 2025 - Client A Tax Filing', max_length=255, unique=True)),
                ('tax_period_start', models.DateField()),
                ('tax_period_end', models.DateField()),
                ('client_reference', models.CharField(blank=True, help_text='External Client ID or Business Name', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ANALYSIS_COMPLETE', 'Analysis Complete'), ('FILED', 'Filed')], default='DRAFT', max_length=50)),
            ],
            options={
                'verbose_name': 'Declaration Entity',
                'verbose_name_plural': 'Declaration Entities',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PROCESSED', max_length=50)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='tax_processor.declaration', verbose_name='Tax Declaration')),
            ],
            options={
                'verbose_name': 'Statement File',
                'verbose_name_plural': 'Statement Files',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255, unique=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower number means higher priority (processed first).')),
                ('declaration_point', models.CharField(help_text="The final tax category (e.g., 'Business Income - Sales')", max_length=255)),
                ('conditions_json', models.JSONField(help_text='JSON array defining field checks and logic.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
                'ordering': ['priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('sender', models.CharField(max_length=255)),
                ('sender_account', models.CharField(blank=True, max_length=50, null=True)),
                ('declaration_point', models.CharField(blank=True, help_text='The tax category assigned by a rule or manual resolution.', max_length=255, null=True)),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='tax_processor.taxrule')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tax_processor.statement')),
            ],
            options={
                'verbose_name': 'Transaction Record',
                'verbose_name_plural': 'Transaction Records',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('RESOLVED', 'Resolved'), ('NEW_RULE_PROPOSED', 'New Rule Proposed')], default='PENDING_REVIEW', max_length=50)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_point', models.CharField(blank=True, help_text='Final category chosen by the reviewer.', max_length=255, null=True)),
                ('rule_proposal_json', models.JSONField(blank=True, help_text='Suggested rule structure based on manual resolution.', null=True)),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Reviewer')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_record', to='tax_processor.transaction', verbose_name='Original Transaction')),
            ],
            options={
                'verbose_name': 'Unmatched Transaction',
                'verbose_name_plural': 'Unmatched Transactions',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('REGULAR_USER', 'Regular User')], default='REGULAR_USER', max_length=50, verbose_name='User Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='System User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
