# Generated by Django 5.2.7 on 2025-10-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0002_declaration_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tax Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Notes/Tax Instruction')),
                ('is_income', models.BooleanField(default=True, verbose_name='Is this an Income Category?')),
            ],
            options={
                'verbose_name': 'Declaration Point (Category)',
                'verbose_name_plural': 'Declaration Points (Categories)',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='declaration_point',
            field=models.ForeignKey(help_text='The final tax category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_processor.declarationpoint'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='declaration_point',
            field=models.ForeignKey(blank=True, help_text='The tax category assigned by a rule or manual resolution.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_processor.declarationpoint'),
        ),
    ]
