# Generated by Django 5.2.7 on 2025-10-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0003_declarationpoint_alter_taxrule_declaration_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='provision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
