# Generated by Django 5.2.7 on 2025-10-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0004_transaction_provision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_rules', to='tax_processor.declaration', verbose_name='Specific Declaration (if not global)'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='proposal_status',
            field=models.CharField(choices=[('NONE', 'Not Proposed'), ('PENDING_GLOBAL', 'Pending Global Approval')], default='NONE', max_length=20, verbose_name='Global Proposal Status'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='name',
            field=models.CharField(help_text='e.g., 2024 - Client A Հայտարարագիր', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='rule_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='taxrule',
            unique_together={('declaration', 'rule_name')},
        ),
    ]
