# Generated by Django 5.2.7 on 2025-11-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0005_taxrule_declaration_taxrule_proposal_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrule',
            options={'ordering': ['priority', 'rule_name'], 'verbose_name': 'Tax Rule (Category)', 'verbose_name_plural': 'Tax Rules (Category)'},
        ),
        migrations.AddField(
            model_name='declaration',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Client First Name'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Client Last Name'),
        ),
        migrations.AddField(
            model_name='declarationpoint',
            name='is_auto_filled',
            field=models.BooleanField(default=False, help_text='Check if this point is pre-filled by tax authorities and not based on transactions.', verbose_name='Automatically filled by tax authority'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='entity_type',
            field=models.CharField(choices=[('UNDETERMINED', 'Not Determined'), ('INDIVIDUAL', 'Individual (Not Legal Entity)'), ('LEGAL', 'Legal Entity')], default='UNDETERMINED', max_length=20, verbose_name='Entity Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_scope',
            field=models.CharField(choices=[('UNDETERMINED', 'Not Determined'), ('LOCAL', 'Local'), ('INTERNATIONAL', 'International')], default='UNDETERMINED', max_length=20, verbose_name='Transaction Scope'),
        ),
        migrations.CreateModel(
            name='EntityTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=100, help_text='Lower number means higher priority.')),
                ('entity_type_result', models.CharField(choices=[('UNDETERMINED', 'Not Determined'), ('INDIVIDUAL', 'Individual (Not Legal Entity)'), ('LEGAL', 'Legal Entity')], default='UNDETERMINED', max_length=20, verbose_name='Resulting Entity Type')),
                ('conditions_json', models.JSONField(help_text='JSON array defining field checks and logic.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entity_rules', to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_entity_rules', to='tax_processor.declaration', verbose_name='Specific Declaration (if not global)')),
            ],
            options={
                'verbose_name': 'Rule (Entity Type)',
                'verbose_name_plural': 'Rules (Entity Type)',
                'ordering': ['priority', 'rule_name'],
                'unique_together': {('declaration', 'rule_name')},
            },
        ),
        migrations.CreateModel(
            name='TransactionScopeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=100, help_text='Lower number means higher priority.')),
                ('scope_result', models.CharField(choices=[('UNDETERMINED', 'Not Determined'), ('LOCAL', 'Local'), ('INTERNATIONAL', 'International')], default='UNDETERMINED', max_length=20, verbose_name='Resulting Scope')),
                ('conditions_json', models.JSONField(help_text='JSON array defining field checks and logic.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scope_rules', to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_scope_rules', to='tax_processor.declaration', verbose_name='Specific Declaration (if not global)')),
            ],
            options={
                'verbose_name': 'Rule (Transaction Scope)',
                'verbose_name_plural': 'Rules (Transaction Scope)',
                'ordering': ['priority', 'rule_name'],
                'unique_together': {('declaration', 'rule_name')},
            },
        ),
    ]
