# Generated by Django 5.2.7 on 2025-11-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0006_alter_taxrule_options_declaration_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=False, verbose_name='Is Expense (Outgoing)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Absolute value of the transaction (always positive)', max_digits=10),
        ),
    ]
