# Generated by Django 5.2.7 on 2025-11-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0008_alter_entitytyperule_entity_type_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_from_description',
            field=models.DateField(blank=True, help_text='Date parsed from the transaction description, if available.', null=True, verbose_name='Date from Description'),
        ),
    ]
