# Generated by Django 5.2.7 on 2025-11-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0009_transaction_date_from_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_type', models.CharField(choices=[('SENDER', 'Frequent Sender'), ('DESCRIPTION', 'Similar Description'), ('AMOUNT', 'Large Amount')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('related_transaction_ids', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='tax_processor.declaration')),
            ],
            options={
                'verbose_name': 'Analysis Hint',
                'verbose_name_plural': 'Analysis Hints',
                'ordering': ['-id'],
            },
        ),
    ]
