# Generated by Django 5.2.7 on 2025-11-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0010_analysishint'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='excel_row_number',
            field=models.IntegerField(blank=True, help_text='The 0-based row index from the source Excel file, for debugging.', null=True, verbose_name='Excel Row Number'),
        ),
    ]
