# Generated by Django 5.2.7 on 2025-11-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0011_transaction_excel_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Place'),
        ),
    ]
