# Generated by Django 5.2.7 on 2025-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0012_transaction_transaction_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysishint',
            name='hint_type',
            field=models.CharField(choices=[('SENDER', 'Frequent Sender'), ('DESCRIPTION', 'Similar Description'), ('AMOUNT', 'Large Amount'), ('AI_SUGGESTION', 'AI Suggestion')], max_length=20),
        ),
    ]
