# Generated by Django 5.2.7 on 2025-12-12 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_processor', '0013_alter_analysishint_hint_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Shared With (Admins)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('REGULAR_USER', 'Regular User')], default='REGULAR_USER', max_length=50, verbose_name='User Role'),
        ),
    ]
